apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD

        command:
        - /bin/sh
        - -c
        - |
          cat <<EOF >/usr/share/nginx/html/index.html
          <html>
          <body style="font-family:Arial">
          <h1>Welcome to Kubernetes!</h1>

          <h2>Application : $APP_NAME</h2>

          <h2>Environment : $ENVIRONMENT</h2>

          <h2>Username : $USERNAME</h2>

          <h2>Password : $PASSWORD</h2>

          </body>
          </html>
          EOF

          nginx -g 'daemon off;'
